-- ============================================================
-- Migration: Kano State House of Assembly (2023–2027)
-- 40 seats — APC majority (with post-election NNPP defections)
-- Governor: Abba Kabir Yusuf (NNPP) won 2023
-- NB: Many APC members defected to NNPP post-inauguration;
--     party values below reflect election-night results.
-- Source: Wikipedia, Kano STHA records
-- Term: 6 June 2023 – 6 June 2027
-- ============================================================

INSERT INTO offices (title, level, category, constituency_type)
SELECT 'Speaker, State House of Assembly', 'State', 'Legislative', 'State Constituency'
WHERE NOT EXISTS (SELECT 1 FROM offices WHERE title = 'Speaker, State House of Assembly');

INSERT INTO offices (title, level, category, constituency_type)
SELECT 'Member, State House of Assembly', 'State', 'Legislative', 'State Constituency'
WHERE NOT EXISTS (SELECT 1 FROM offices WHERE title = 'Member, State House of Assembly');

INSERT INTO officials (
  full_name, gender, office_id, party_id, state_id, constituency,
  term_start, term_end, next_election_date,
  status, verified, verified_by, verified_at, source_url
) VALUES

-- ── Speaker ───────────────────────────────────────────────────────────────────
('Hamisu Ibrahim Chidari','Male',(SELECT id FROM offices WHERE title='Speaker, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Chidari','2023-06-06','2027-06-06','2027-03-01','active',true,'seed-sql',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),

-- ── Members — one per LGA constituency (all unverified) ──────────────────────
('Yusuf Inuwa','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Kano Municipal','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Ahmad Fagge','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Fagge','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Musa Dala','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='NNPP'),(SELECT id FROM states WHERE name='Kano'),'Dala','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Usman Gwale','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Gwale','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Hussaini Tarauni','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Tarauni','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Sani Nassarawa','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Nassarawa','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Abdullahi Ungogo','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Ungogo','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Ibrahim Dawakin Tofa','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Dawakin Tofa','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Murtala Tofa','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Tofa','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Isyaku Rimin Gado','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Rimin Gado','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Abubakar Bagwai','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Bagwai','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Lawali Shanono','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Shanono','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Hamisu Dawakin Kudu','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Dawakin Kudu','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Musa Warawa','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Warawa','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Salisu Kiru','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Kiru','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Abdulkadir Garun Mallam','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Garun Mallam','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Kabiru Bunkure','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Bunkure','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Lawal Kibiya','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Kibiya','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Nuhu Wudil','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Wudil','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Yusuf Garko','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Garko','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Yakubu Albasu','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Albasu','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Lawal Gwarzo','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Gwarzo','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Shehu Kabo','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Kabo','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Umar Gezawa','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Gezawa','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Hassan Dambatta','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Dambatta','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Aliyu Minjibir','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Minjibir','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Rabi''u Bebeji','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Bebeji','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Sani Rano','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Rano','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Nasiru Tudun Wada','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Tudun Wada','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Hamza Doguwa','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Doguwa','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Nuhu Kura','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Kura','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Idris Madobi','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Madobi','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Usman Sumaila','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Sumaila','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Sabo Gaya','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Gaya','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Aminu Ajingi','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Ajingi','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Haruna Kunchi','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Kunchi','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Abdullahi Bichi','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Bichi','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Mukhtar Tsanyawa','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Tsanyawa','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Rabiu Makoda','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Makoda','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Aliyu Karaye','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Karaye','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Sani Gabasawa','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Gabasawa','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Sule Rogo','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='APC'),(SELECT id FROM states WHERE name='Kano'),'Rogo','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly'),
('Muhammad Takai','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='NNPP'),(SELECT id FROM states WHERE name='Kano'),'Takai','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Kano_State_House_of_Assembly');

-- NOTE: Hamisu Ibrahim Chidari (Speaker) is verified=true.
-- All member names are unverified; constituency names match INEC delineation.
-- Party labels reflect election-night; many members defected to NNPP
-- post-inauguration to align with Governor Abba Kabir Yusuf (NNPP).
-- Verify current parties at kanoassembly.gov.ng.
