-- ============================================================
-- Migration: Delta State House of Assembly (2023–2027)
-- 29 seats — PDP majority
-- Governor: Sheriff Oborevwori (PDP) won 2023
-- Source: Delta State House of Assembly, Wikipedia
-- Term: 6 June 2023 – 6 June 2027
-- ============================================================

INSERT INTO offices (title, level, category, constituency_type)
SELECT 'Speaker, State House of Assembly', 'State', 'Legislative', 'State Constituency'
WHERE NOT EXISTS (SELECT 1 FROM offices WHERE title = 'Speaker, State House of Assembly');

INSERT INTO offices (title, level, category, constituency_type)
SELECT 'Member, State House of Assembly', 'State', 'Legislative', 'State Constituency'
WHERE NOT EXISTS (SELECT 1 FROM offices WHERE title = 'Member, State House of Assembly');

INSERT INTO officials (
  full_name, gender, office_id, party_id, state_id, constituency,
  term_start, term_end, next_election_date,
  status, verified, verified_by, verified_at, source_url
) VALUES

-- ── Speaker ───────────────────────────────────────────────────────────────────
('Emomotimi Guwor','Male',(SELECT id FROM offices WHERE title='Speaker, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='PDP'),(SELECT id FROM states WHERE name='Delta'),'Warri South II','2023-06-06','2027-06-06','2027-03-01','active',true,'seed-sql',NOW(),'https://en.wikipedia.org/wiki/Delta_State_House_of_Assembly'),

-- ── Members — unverified; require confirmation ────────────────────────────────
('Ekpete Oboro','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='PDP'),(SELECT id FROM states WHERE name='Delta'),'Oshimili North','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Delta_State_House_of_Assembly'),
('Victor Osoka','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='PDP'),(SELECT id FROM states WHERE name='Delta'),'Oshimili South I','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Delta_State_House_of_Assembly'),
('Chukwuemeka Nwaobi','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='PDP'),(SELECT id FROM states WHERE name='Delta'),'Oshimili South II','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Delta_State_House_of_Assembly'),
('Henry Omase','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='PDP'),(SELECT id FROM states WHERE name='Delta'),'Aniocha North','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Delta_State_House_of_Assembly'),
('Ned Nwosu','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='PDP'),(SELECT id FROM states WHERE name='Delta'),'Aniocha South I','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Delta_State_House_of_Assembly'),
('Emeka Nwosu','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='PDP'),(SELECT id FROM states WHERE name='Delta'),'Aniocha South II','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Delta_State_House_of_Assembly'),
('Chris Ossai','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='PDP'),(SELECT id FROM states WHERE name='Delta'),'Ika North-East I','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Delta_State_House_of_Assembly'),
('Smart Obende','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='PDP'),(SELECT id FROM states WHERE name='Delta'),'Ika North-East II','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Delta_State_House_of_Assembly'),
('Festus Okiemute','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='PDP'),(SELECT id FROM states WHERE name='Delta'),'Ika South','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Delta_State_House_of_Assembly'),
('Solomon Oghuma','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='PDP'),(SELECT id FROM states WHERE name='Delta'),'Ndokwa East','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Delta_State_House_of_Assembly'),
('Victor Nwosu','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='PDP'),(SELECT id FROM states WHERE name='Delta'),'Ndokwa West','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Delta_State_House_of_Assembly'),
('Monday Igbuya','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='PDP'),(SELECT id FROM states WHERE name='Delta'),'Ukwuani','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Delta_State_House_of_Assembly'),
('Reuben Izeze','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='PDP'),(SELECT id FROM states WHERE name='Delta'),'Isoko North','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Delta_State_House_of_Assembly'),
('Oboro Preyor','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='PDP'),(SELECT id FROM states WHERE name='Delta'),'Isoko South I','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Delta_State_House_of_Assembly'),
('Elias Oboro','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='PDP'),(SELECT id FROM states WHERE name='Delta'),'Isoko South II','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Delta_State_House_of_Assembly'),
('Chuks Ossai','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='PDP'),(SELECT id FROM states WHERE name='Delta'),'Ethiope East','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Delta_State_House_of_Assembly'),
('Rueben Ufuoma','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='PDP'),(SELECT id FROM states WHERE name='Delta'),'Ethiope West','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Delta_State_House_of_Assembly'),
('Patience Ekughena','Female',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='PDP'),(SELECT id FROM states WHERE name='Delta'),'Sapele I','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Delta_State_House_of_Assembly'),
('Taribi Ughwanogho','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='PDP'),(SELECT id FROM states WHERE name='Delta'),'Sapele II','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Delta_State_House_of_Assembly'),
('Sylvester Odibo','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='PDP'),(SELECT id FROM states WHERE name='Delta'),'Okpe','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Delta_State_House_of_Assembly'),
('Ovuorie Johnson','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='PDP'),(SELECT id FROM states WHERE name='Delta'),'Uvwie I','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Delta_State_House_of_Assembly'),
('Solomon Emu','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='PDP'),(SELECT id FROM states WHERE name='Delta'),'Uvwie II','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Delta_State_House_of_Assembly'),
('Augustine Okorefe','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='PDP'),(SELECT id FROM states WHERE name='Delta'),'Udu','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Delta_State_House_of_Assembly'),
('Taiye Otuaro','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='PDP'),(SELECT id FROM states WHERE name='Delta'),'Warri South I','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Delta_State_House_of_Assembly'),
('Anthony Elekeokwuri','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='PDP'),(SELECT id FROM states WHERE name='Delta'),'Warri North','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Delta_State_House_of_Assembly'),
('Omene Julius','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='PDP'),(SELECT id FROM states WHERE name='Delta'),'Warri South-West','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Delta_State_House_of_Assembly'),
('Reuben Uwejeyan','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='PDP'),(SELECT id FROM states WHERE name='Delta'),'Ughelli North I','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Delta_State_House_of_Assembly'),
('David Onoriode','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='PDP'),(SELECT id FROM states WHERE name='Delta'),'Ughelli North II','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Delta_State_House_of_Assembly'),
('Ovuozorie Macaulay','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='PDP'),(SELECT id FROM states WHERE name='Delta'),'Ughelli South','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Delta_State_House_of_Assembly'),
('Moses Efemwonhieki','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='PDP'),(SELECT id FROM states WHERE name='Delta'),'Bomadi','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Delta_State_House_of_Assembly'),
('Felix Boroh','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='PDP'),(SELECT id FROM states WHERE name='Delta'),'Burutu I','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Delta_State_House_of_Assembly'),
('Eferiere Igho','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='PDP'),(SELECT id FROM states WHERE name='Delta'),'Burutu II','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Delta_State_House_of_Assembly'),
('Henry Seriake','Male',(SELECT id FROM offices WHERE title='Member, State House of Assembly' LIMIT 1),(SELECT id FROM parties WHERE abbreviation='PDP'),(SELECT id FROM states WHERE name='Delta'),'Patani','2023-06-06','2027-06-06','2027-03-01','active',false,'seed-sql-unverified',NOW(),'https://en.wikipedia.org/wiki/Delta_State_House_of_Assembly');

-- NOTE: Emomotimi Guwor (Speaker) is verified=true.
-- All other member names are unverified; confirm at deltastateassembly.gov.ng.
-- Party split: PDP near-total majority.
